### ISSUE TITLE
Elements included in `game_state` are unpredictable

### ISSUE THREAD

**Issue by LswaN58** [widVE/ExploringTheUniverseVR#5]
This is really weird.
1. The `game_state` always includes "seconds_from_launch."
2. The `game_state` _sometimes_ includes "scene_name" but *not* "rotX", "rotY", etc.
3. The `game_state` _sometimes_ includes "rotX", "rotY", etc. but *not* "scene_name"
4. The `game_state` _sometimes_ includes both.

What is put in there is unpredictable, even _within a single event type_. That is, I've observed cases 2, 3, and 4 within a single gameplay session, all in the `viewport_data` event.

This suggests the issue is not just an oversight, missing one kind of event. There is something significantly wrong happening.

**Comment by LswaN58** [comment]
Three sample events, showing the three cases:

|case | id    | session_id        | event_name           | game_state    | client_time         | app_version | log_version |
|---| ---| ---| ---| ---| ---| ---| ---|
|all | 28182 | 23021311421083804 | viewport_data        | {"seconds_from_launch":"5.981","scene_name":"ICE","rotX":"-0.734","rotY":"0.265","rotZ":"-0.459","rotW":"-0.424"} | 2023-02-13 17:42:15 |         213 |           1 |
| no rotation | 28183 | 23021311421083804 | viewport_data        | {"seconds_from_launch":"5.981","scene_name":"ICE"}                                                                | 2023-02-13 17:42:17 |         213 |           1 |
| no scene | 28189 | 23021311421083804 | viewport_data        | {"seconds_from_launch":"11.438","rotX":"-0.030","rotY":"-0.220","rotZ":"0.010","rotW":"0.975"}                    | 2023-02-13 17:42:22 |         213 |           1 |

**Comment by rossTnick** [comment]
6a4a3d8409a132876fb85f1136152e9e3e30f26a
